export type Topic = { label: string; link: string; isAvailable?: boolean };

export const topics: Topic[] = [
  { label: "React - это...", link: "react-is", isAvailable: true },
  { label: "С чего начать?", link: "where-to-start" },
  { label: "Структура проекта", link: "project-structure" },
  { label: "Введение в VirtualDOM", link: "introduction-to-virtualdom" },
  { label: "Components", link: "components" },
  { label: "Props", link: "props" },
  { label: "State (useState)", link: "state-usestate" },
  { label: "LifeCycle (useEffect)", link: "lifecycle-useeffect" },
  {
    label: "Events и как работать с ними",
    link: "events-and-how-to-work-with-them",
  },
  {
    label: "Refs, Fragment, key, React.memo, useMemo, ...",
    link: "refs-fragment-key-react-memo-usememo",
  },
  { label: "Context (useContext)", link: "context-usecontext" },
  { label: "React Router V6", link: "react-router-v6" },
  { label: "react-hook-form vs formik", link: "react-hook-form-vs-formik" },
  {
    label: "Про STORAGEs (Local Storage, Session Storage, Local Forage, ...)",
    link: "about-storages-local-session-local-forage",
  },
  { label: "HOC", link: "hoc", isAvailable: true },
  { label: "Flux", link: "flux" },
  {
    label: "React-Redux: actions, reducers, store,...",
    link: "react-redux-actions-reducers-store",
  },
  { label: "Middleware (Redux Thunk)", link: "middleware-redux-thunk" },
  { label: "RTK: Redux Toolkit", link: "rtk-redux-toolkit" },
  { label: "RTK: Query&Mutation", link: "rtk-query-and-mutation" },
  { label: "Защита чек-листа React", link: "react-checklist-security" },
  { label: "Защита чек-листа RTK", link: "rtk-checklist-security" },
  { label: "To Do List (RTK)", link: "to-do-list-rtk" },
  { label: "To Do List (RTK + API)", link: "to-do-list-rtk-api" },
  {
    label: "Pagination & Infinite scroll",
    link: "pagination-and-infinite-scroll",
  },
  { label: "YouTube SPA (своими)", link: "youtube-spa-custom" },
  { label: "Hacker News (своими)", link: "hacker-news-custom" },
  { label: "Три типа вызовов", link: "three-types-of-calls" },
  { label: "TYP v1", link: "typ-v1" },
  { label: "Deploy", link: "deploy" },
  {
    label: "Tailwind CSS, Styled Components",
    link: "tailwind-css-styled-components",
  },
  { label: "ANTD vs MUI", link: "antd-vs-mui" },
  { label: "Тестирование: Jest и Enzyme", link: "testing-jest-and-enzyme" },
  { label: "AXIOS", link: "axios" },
];
